### ISSUE TITLE
[BUG] Zone Layers are only based on the first scenario

### ISSUE THREAD

**Issue by AwesomeTMC** [SuperHackio/Scenaristar#6]
Scenaristar 1.5's Zone Layers seems to be broken. Changing the zone layers of one scenario changes it for every scenario. Here I have the same file open in different versions of Scenaristar, yet the zone layers are clearly different. This happens regardless of the game.
![image](https://github.com/SuperHackio/Scenaristar/assets/38051573/9150bf21-4d21-45d5-b684-a61d8e452091)

**Comment by SuperHackio** [comment]
I know I fixed this already but I wanted to provide actual insight as to what happened

It's actually not corrupting your data like you claim. It's only a visual bug, as switching what zone you have selected will update it to what it should be. The fix is to simply refresh zone list each time you change scenarios.
